from enum import Enum

class ScenarioState(str, Enum):
    BRIEFING = "BRIEFING"
    ACTIVE = "ACTIVE"
    DEGRADED = "DEGRADED"
    DECISION_WINDOW = "DECISION_WINDOW"
    RECOVERY = "RECOVERY"
    RESOLUTION = "RESOLUTION"
    AAR_READY = "AAR_READY"

class RoleEnum(str, Enum):
    INSTRUCTOR = "INSTRUCTOR"
    TEAM_LEAD = "TEAM_LEAD"
    COORDINATION = "COORDINATION"
    INFORMATION = "INFORMATION"

class DegradationType(str, Enum):
    DELAY = "DELAY"
    DROPOUT = "DROPOUT"
    INTERMITTENT = "INTERMITTENT"
    CONTRADICTION = "CONTRADICTION"
    STALENESS = "STALENESS"
    PARTIAL_PAYLOAD = "PARTIAL_PAYLOAD"
    RECOVERY = "RECOVERY"

class ConfidenceLevel(str, Enum):
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"

class DecisionType(str, Enum):
    ACTION_DISPATCH = "ACTION_DISPATCH"
    HOLD_POSITION = "HOLD_POSITION"
    REQUEST_INFORMATION = "REQUEST_INFORMATION"
    ESCALATE_COMMAND = "ESCALATE_COMMAND"
    RECON_CONFIRM = "RECON_CONFIRM"

class SourceType(str, Enum):
    OPTICAL_FEED = "OPTICAL_FEED"
    RADAR_TELEMETRY = "RADAR_TELEMETRY"
    HUMINT_DISPATCH = "HUMINT_DISPATCH"
    SIGINT_SENSOR = "SIGINT_SENSOR"
    EW_INTERCEPT = "EW_INTERCEPT"
    CYBER_STATUS = "CYBER_STATUS"

class DeliveryStatus(str, Enum):
    DELIVERED = "DELIVERED"
    DELAYED = "DELAYED"
    DROPPED = "DROPPED"
    STALE = "STALE"
    CONFLICT = "CONFLICT"
    RECOVERED = "RECOVERED"

class EventType(str, Enum):
    WORLD_EVENT = "WORLD_EVENT"
    INFORMATION_GENERATED = "INFORMATION_GENERATED"
    INFORMATION_DELIVERED = "INFORMATION_DELIVERED"
    INFORMATION_DELAYED = "INFORMATION_DELAYED"
    INFORMATION_DROPPED = "INFORMATION_DROPPED"
    INFORMATION_CONFLICT = "INFORMATION_CONFLICT"
    INFORMATION_RECOVERED = "INFORMATION_RECOVERED"
    DEGRADATION_STARTED = "DEGRADATION_STARTED"
    DEGRADATION_UPDATED = "DEGRADATION_UPDATED"
    DEGRADATION_ENDED = "DEGRADATION_ENDED"
    MESSAGE_SENT = "MESSAGE_SENT"
    MESSAGE_ACKNOWLEDGED = "MESSAGE_ACKNOWLEDGED"
    DECISION_SUBMITTED = "DECISION_SUBMITTED"
    DECISION_REVISED = "DECISION_REVISED"
    OBJECTIVE_UPDATED = "OBJECTIVE_UPDATED"
    SESSION_STARTED = "SESSION_STARTED"
    SESSION_PAUSED = "SESSION_PAUSED"
    SESSION_RESUMED = "SESSION_RESUMED"
    SESSION_ENDED = "SESSION_ENDED"
